local:
  gcp:
    version: 1.0.0.RELEASE

logging:
  level:
    org.springframework.core.env: warn
    org.springframework.jndi: warn

server:
  compression:
    enabled: true
    mime-types: application/json,text/css,text/html
    min-response-size: 2048
  use-forward-headers: true

spring:
  jackson:
    serialization:
     write-dates-as-timestamps: false
  resources:
    chain:
      strategy:
        content:
          enabled: true

initializr:
  env:
    boms:
      azure:
        groupId: com.microsoft.azure
        artifactId: azure-spring-boot-bom
        versionProperty: azure.version
        mappings:
          - versionRange: "[1.5.4.RELEASE,2.0.0.RELEASE)"
            version: 0.2.4
          - versionRange: "2.0.0.RELEASE"
            version: 2.0.5
      codecentric-spring-boot-admin:
        groupId: de.codecentric
        artifactId: spring-boot-admin-dependencies
        versionProperty: spring-boot-admin.version
        mappings:
          - versionRange: "[1.5.9.RELEASE,2.0.0.M1)"
            version: 1.5.7
          - versionRange: "[2.0.0.M1,2.1.0.M1)"
            version: 2.0.2
          - versionRange: "2.1.0.M1"
            version: 2.1.0-SNAPSHOT
            repositories: sonatype-snapshots
      keycloak:
        groupId: org.keycloak.bom
        artifactId: keycloak-adapter-bom
        versionProperty: keycloak.version
        mappings:
          - versionRange : "[1.5.3.RELEASE,2.0.0.M1)"
            version: 3.4.2.Final
          - versionRange : "2.0.0.M1"
            version: 4.2.0.Final
      spring-cloud:
        groupId: org.springframework.cloud
        artifactId: spring-cloud-dependencies
        versionProperty: spring-cloud.version
        order: 50
        mappings:
          - versionRange: "[1.2.3.RELEASE,1.3.0.RELEASE)"
            version: Angel.SR6
          - versionRange: "[1.3.0.RELEASE,1.4.0.RELEASE)"
            version: Brixton.SR7
          - versionRange: "[1.4.0.RELEASE,1.4.x.RELEASE]"
            version: Camden.SR7
          - versionRange: "[1.5.0.RELEASE,1.5.x.RELEASE]"
            version: Edgware.SR4
          - versionRange: "[1.5.x.BUILD-SNAPSHOT,2.0.0.M1)"
            version: Edgware.BUILD-SNAPSHOT
            repositories: spring-snapshots,spring-milestones
          - versionRange: "[2.0.0.M3, 2.0.0.M5)"
            version: Finchley.M2
            repositories: spring-milestones
          - versionRange: "[2.0.0.M5, 2.0.0.M5]"
            version: Finchley.M3
            repositories: spring-milestones
          - versionRange: "[2.0.0.M6, 2.0.0.M6]"
            version: Finchley.M4
            repositories: spring-milestones
          - versionRange: "[2.0.0.M7, 2.0.0.M7]"
            version: Finchley.M5
            repositories: spring-milestones
          - versionRange: "[2.0.0.RC1, 2.0.0.RC1]"
            version: Finchley.M6
            repositories: spring-milestones
          - versionRange: "[2.0.0.RC2,2.0.0.RC2]"
            version: Finchley.M7
            repositories: spring-milestones
          - versionRange: "[2.0.0.RELEASE,2.0.0.RELEASE]"
            version: Finchley.M9
            repositories: spring-milestones
          - versionRange: "[2.0.1.RELEASE,2.0.2.RELEASE)"
            version: Finchley.RC1
            repositories: spring-milestones
          - versionRange: "[2.0.2.RELEASE,2.0.3.RELEASE)"
            version: Finchley.RC2
            repositories: spring-milestones
          - versionRange: "[2.0.3.RELEASE,2.0.x.BUILD-SNAPSHOT)"
            version: Finchley.SR1
          - versionRange: "[2.0.x.BUILD-SNAPSHOT,2.1.0.M1)"
            version: Finchley.BUILD-SNAPSHOT
            repositories: spring-snapshots,spring-milestones
          - versionRange: "2.1.0.M1"
            version: Greenwich.BUILD-SNAPSHOT
            repositories: spring-snapshots,spring-milestones
      spring-cloud-gcp:
        groupId: org.springframework.cloud
        artifactId: spring-cloud-gcp-dependencies
        versionProperty: spring-cloud-gcp.version
        additionalBoms: [spring-cloud]
        version: ${local.gcp.version}
        repositories: spring-milestones
      spring-cloud-services:
        groupId: io.pivotal.spring.cloud
        artifactId: spring-cloud-services-dependencies
        versionProperty: spring-cloud-services.version
        additionalBoms: [spring-cloud]
        mappings:
          - versionRange: "[1.3.0.RELEASE,1.4.0.RELEASE)"
            version: 1.2.1.RELEASE
          - versionRange: "[1.4.0.RELEASE,1.4.x.RELEASE]"
            version: 1.5.0.RELEASE
          - versionRange: "[1.5.0.RELEASE,1.5.x.BUILD-SNAPSHOT]"
            version: 1.6.3.RELEASE
          - versionRange: "[2.0.0.RELEASE,2.0.x.RELEASE]"
            version: 2.0.1.RELEASE
          - versionRange: "2.0.x.BUILD-SNAPSHOT"
            version: 2.0.2.BUILD-SNAPSHOT
            repositories: spring-snapshots,spring-milestones
      spring-cloud-task:
        groupId: org.springframework.cloud
        artifactId: spring-cloud-task-dependencies
        versionProperty: spring-cloud-task.version
        order: 30
        mappings:
          - versionRange: "[1.3.0.RELEASE, 1.4.0.RELEASE]"
            version: 1.0.3.RELEASE
          - versionRange: "[1.4.0.RELEASE, 1.5.0.RC1)"
            version: 1.1.2.RELEASE
          - versionRange: "[1.5.0.RC1, 2.0.0.M1)"
            version: 1.2.3.RELEASE
          - versionRange: "[2.0.0.M2, 2.0.0.RELEASE)"
            version: 2.0.0.M3
            repositories: spring-milestones
          - versionRange: "2.0.0.RELEASE"
            version: 2.0.0.RELEASE
      spring-statemachine:
        groupId: org.springframework.statemachine
        artifactId: spring-statemachine-bom
        versionProperty: spring-statemachine.version
        mappings:
          - versionRange: "[2.0.0.RC1,2.0.0.RC1]"
            version: 2.0.0.M4
            repositories: spring-milestones
          - versionRange: "[2.0.0.RC2,2.0.0.RC2]"
            version: 2.0.0.M5
            repositories: spring-milestones
          - versionRange: "2.0.0.RELEASE"
            version: 2.0.1.RELEASE
      vaadin:
        groupId: com.vaadin
        artifactId: vaadin-bom
        versionProperty: vaadin.version
        mappings:
          - versionRange: "[1.3.0.RELEASE, 1.5.0.M1)"
            version: 7.7.7
          - versionRange: "[1.5.0.M1,2.0.0.M1)"
            version: 8.4.4
          - versionRange: "2.0.0.M1"
            version: 10.0.5
    gradle:
      dependency-management-plugin-version: 0.6.0.RELEASE
    kotlin:
      default-version: 1.2.61
      mappings:
        - versionRange: "[1.5.0.RELEASE,2.1.0.M1)"
          version: 1.2.51
    repositories:
      sonatype-snapshots:
        name: Sonatype Snapshots
        url: https://oss.sonatype.org/content/repositories/snapshots/
        snapshotsEnabled: true
  dependencies:
    #web模块
    - name: Spring
      content:
        - name: Web
          id: web
          description: Full-stack web development with Tomcat and Spring MVC
          weight: 100
          facets:
            - web
            - json
          links:
            - rel: guide
              href: https://spring.io/guides/gs/rest-service/
              description: Building a RESTful Web Service
            - rel: reference
              href: http://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-developing-web-applications
            - rel: guide
              href: https://spring.io/guides/gs/serving-web-content/
              description: Serving Web Content with Spring MVC
            - rel: guide
              href: https://spring.io/guides/tutorials/bookmarks/
              description: Building REST services with Spring
        - name: Aspects
          id: aop
          description: Create your own Aspects using Spring AOP and AspectJ
    #远程调用
    - name: 远程RPC
      content:
      - name: Dubbo
        id: dubbo
        description: Full-stack web development with Tomcat and Spring MVC
        weight: 100
        facets:
        - web
        - json
        links:
        - rel: guide
          href: https://spring.io/guides/gs/rest-service/
          description: Building a RESTful Web Service
        - rel: reference
          href: http://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-developing-web-applications
        - rel: guide
          href: https://spring.io/guides/gs/serving-web-content/
          description: Serving Web Content with Spring MVC
        - rel: guide
          href: https://spring.io/guides/tutorials/bookmarks/
          description: Building REST services with Spring
      - name: Hessian
        id: hessian
        description: Create your own Aspects using Spring AOP and AspectJ
    # 数据库
    - name: 数据库
      content:
      - name: MySql
        id: mysql
        description: MySQL JDBC driver
        groupId: mysql
        artifactId: mysql-connector-java
        scope: runtime
        starter: false
        links:
        - rel: guide
          href: https://spring.io/guides/gs/accessing-data-mysql/
          description: Accessing data with MySQL
      - name: MyBatis
        id: mybatis
        description: Persistence support using MyBatis
        links:
        - rel: guide
          href: https://github.com/mybatis/spring-boot-starter/wiki/Quick-Start
          description: Quick Start
        - rel: reference
          href: http://www.mybatis.org/spring-boot-starter/mybatis-spring-boot-autoconfigure/
        groupId: org.mybatis.spring.boot
        artifactId: mybatis-spring-boot-starter
        mappings:
        - versionRange: "[1.3.0.RELEASE,1.4.0.RELEASE)"
          version: 1.1.1
        - versionRange: "[1.4.0.RELEASE,1.5.0.RELEASE)"
          version: 1.2.2
        - versionRange: 1.5.0.RELEASE
          version: 1.3.2
      - name: JDBC
        id: jdbc
        description: JDBC databases, support transaction. It is included when use mybtais.
        links:
        - rel: guide
          href: https://spring.io/guides/gs/relational-data-access/
          description: Accessing Relational Data using JDBC with Spring
        - rel: guide
          href: https://spring.io/guides/gs/managing-transactions/
          description: Managing Transactions
        - rel: reference
          href: http://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-sql
      - name: tk-Mapper
        id: tkMapper
        description: tk mapper.可以极其方便的使用MyBatis单表的增删改查。
        links:
        - rel: guide
          href: https://github.com/abel533/Mapper
          description: 官方github
        - rel: reference
          href: https://github.com/abel533/Mapper/wiki
          description: 用户手册
    - name: NoSQL
      content:
        - name: Redis
          id: data-redis
          description: Redis key-value data store, including spring-data-redis
          aliases:
            - redis
          mappings:
            - versionRange: 1.4.0.M1
              artifactId: spring-boot-starter-data-redis
            - versionRange: "[1.1.5.RELEASE,1.4.0.M1)"
              artifactId: spring-boot-starter-redis
          links:
            - rel: guide
              href: https://spring.io/guides/gs/messaging-redis/
              description: Messaging with Redis
            - rel: reference
              href: http://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-redis
        - name: MongoDB
          id: data-mongodb
          description: MongoDB NoSQL Database, including spring-data-mongodb
          weight: 50
          links:
            - rel: guide
              href: https://spring.io/guides/gs/accessing-data-mongodb/
              description: Accessing Data with MongoDB
            - rel: reference
              href: http://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-mongodb
        - name: Elasticsearch
          id: data-elasticsearch
          description: Elasticsearch search and analytics engine including spring-data-elasticsearch
          weight: 10
          links:
            - rel: reference
              href: http://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-elasticsearch
    - name: MQ
      content:
        - name: RabbitMQ
          id: amqp
          description: Advanced Message Queuing Protocol via spring-rabbit
          weight: 100
          keywords:
            - messaging
          links:
            - rel: guide
              href: https://spring.io/guides/gs/messaging-rabbitmq/
              description: Messaging with RabbitMQ
            - rel: reference
              href: http://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-amqp
        - name: Kafka
          id: kafka
          weight: 100
          description: Kafka messaging support using Spring Kafka
          versionRange: 1.5.0.RC1
          groupId: org.springframework.kafka
          artifactId: spring-kafka
          starter: false
          keywords:
            - messaging
          links:
            - rel: reference
              href: http://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-kafka
        - name: Kafka Streams
          id: kafka-streams
          weight: 90
          description: Support for building stream processing applications with Apache Kafka Streams
          versionRange: 2.0.0.RELEASE
          groupId: org.apache.kafka
          artifactId: kafka-streams
          starter: false
          links:
            - rel: guide
              href: https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/kafka-streams-samples
              description: Samples for using Kafka Streams with Spring Cloud stream
            - rel: reference
              href: https://docs.spring.io/spring-kafka/docs/current/reference/html/_reference.html#kafka-streams
              description: Kafka Streams Support in Spring Kafka
            - rel: reference
              href: https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#_kafka_streams_binding_capabilities_of_spring_cloud_stream
              description: Kafka Streams Binding Capabilities of Spring Cloud Stream
    - name: 工具包
      content:
        - name: 上上签工具包
          id: ssq-util
        - name: google工具包guava
          id: guava
        - name: common-util
          id: common-util
        - name: Swagger
          id: Swagger
  types:
    - name: Maven Project
      id: maven-project
      description: Generate a Maven based project archive
      sts-id: starter.zip
      tags:
        build: maven
        format: project
      default: true
      action: /starter.zip
    - name: Maven POM
      id: maven-build
      description: Generate a Maven pom.xml
      sts-id: pom.xml
      tags:
        build: maven
        format: build
      default: false
      action: /pom.xml
    - name: Gradle Project
      id: gradle-project
      description: Generate a Gradle based project archive
      sts-id: gradle.zip
      tags:
        build: gradle
        format: project
      default: false
      action: /starter.zip
    - name: Gradle Config
      id: gradle-build
      description: Generate a Gradle build file
      sts-id: build.gradle
      tags:
        build: gradle
        format: build
      default: false
      action: /build.gradle
  packagings:
    - name: Jar
      id: jar
      default: true
    - name: War
      id: war
      default: false
  javaVersions:
    - id: 10
      name: Java10
      default: false
    - id: 1.8
      name: 8
      default: true
  languages:
    - name: Java
      id: java
      default: true
    - name: Kotlin
      id: kotlin
      default: false
    - name: Groovy
      id: groovy
      default: false
  bootVersions:
    - name : Latest SNAPSHOT
      id: 1.2.4.BUILD-SNAPSHOT
      default: false
    - name: 1.2.3
      id: 1.2.3.RELEASE
      default: true
    - name: 1.1.12
      id: 1.1.12.RELEASE
      default: false
